[package]
name = "revdl"
version = "0.1.0"
authors = ["revinder-mk <michal0kasprzyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subprocess = "0.2.8"
clap = "3.0.0-beta.5"
term-painter = "0.3.0"