[package]
name = "revdl"
version = "0.1.0"
authors = ["revinder-mk <michal0kasprzyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
youtube_dl = "0.6.3"
subprocess = "0.2.8"